# Generated by Django 3.2.18 on 2023-04-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt', '0002_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='category',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
